# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS
BRAINTREE_MERCHANT_ID: '75mm7wctqfgs2mmk'
BRAINTREE_PUBLIC_KEY: 'sm9ynqyr8x64zjrk'
BRAINTREE_PRIVATE_KEY: 'd1bee2da6c69e0ecf1013bd8458484ad'